/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funciones;

import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author JuanC09 
 */
public class new_persona extends javax.swing.JFrame {

    /**
     * Creates new form new_persona
     */
    private File fichero;
    private principal pri;
    public new_persona() {
        initComponents();
        this.fichero = null;
    }
    
    public new_persona(principal p){
        initComponents();
        this.pri = p;
    }

    public File getFichero() {
        return fichero;
    }

    public void setFichero(File fichero) {
        this.fichero = fichero;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtNdoc = new javax.swing.JTextField();
        jcTdoc = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtCelular = new javax.swing.JTextField();
        jtNombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtApellidos = new javax.swing.JTextField();
        jtEmail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("AGREGAR PERSONA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 20, 270, 30);

        jPanel1.setBackground(new java.awt.Color(34, 132, 132));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS PERSONALES"));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. Documento:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 74, 100, 30);
        jPanel1.add(jtNdoc);
        jtNdoc.setBounds(140, 80, 300, 30);

        jcTdoc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "R.C.", "T.I.", "C.C.", "C.E." }));
        jPanel1.add(jcTdoc);
        jcTdoc.setBounds(140, 40, 100, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo Documento:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 40, 100, 14);

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Nombres:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 130, 90, 14);
        jPanel1.add(jtCelular);
        jtCelular.setBounds(140, 240, 300, 30);
        jPanel1.add(jtNombres);
        jtNombres.setBounds(140, 120, 300, 30);

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("No Celular:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 100, 14);

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Apellidos:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 154, 90, 30);

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Email:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 200, 80, 20);
        jPanel1.add(jtApellidos);
        jtApellidos.setBounds(140, 160, 300, 30);
        jPanel1.add(jtEmail);
        jtEmail.setBounds(140, 200, 300, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 60, 630, 310);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 400, 120, 23);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(520, 400, 110, 23);

        setBounds(0, 0, 704, 485);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        for (int i = 0; i < pri.persona.length; i++){ 
            if(pri.persona[i] == null){
                Persona per = new Persona();
                 per.setTipo_doc(jcTdoc.getSelectedItem().toString());
                 per.setNumero_doc(jtNdoc.getText());
                 per.setNombres(jtNombres.getText());
                 per.setApellidos(jtApellidos.getText());
                 per.setEmail(jtEmail.getText());
                 per.setCelular(jtCelular.getText());
                 pri.persona[i] = per;
                 
            
                 
                 jtNdoc.setText("");
                 jtNombres.setText("");
                 jtApellidos.setText("");
                 jtEmail.setText("");
                 jtCelular.setText("");
                 
                 JOptionPane.showMessageDialog(null,"Persona guardada");
                 break;
            }
            
        }
                 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(new_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(new_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(new_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(new_persona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new new_persona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox jcTdoc;
    private javax.swing.JTextField jtApellidos;
    private javax.swing.JTextField jtCelular;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtNdoc;
    private javax.swing.JTextField jtNombres;
    // End of variables declaration//GEN-END:variables
}
